# hyper
xla: true
amp: false
checkpoint:
  subdir: 'ckpt'
  max_to_keep: 5
  name: 'ckpt'
tflog:
  subdir: 'tflogs'
use_synthetic_data: false
seed: null
solver:
  steps_per_loop: 100
  evaluate_interval: 1.0